services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  node: 
    container_name: node
    build: .
    restart: always
    ports: 
      - 4000:4000
    depends_on: 
      - db

volumes:
  my-db:
